# Generated by Django 5.2.7 on 2025-10-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_tasks', to='tasks.employee', verbose_name='Адресаты'),
        ),
    ]
