# Generated by Django 5.2.7 on 2025-10-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_eventcard_task_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
