# Generated by Django 5.2.7 on 2025-10-22 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_eventcard_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='created_at',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
