# Generated by Django 5.2.7 on 2025-10-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_eventcard_created_at_eventcard_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='progress',
        ),
    ]
