# Generated by Django 5.2.7 on 2025-10-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_eventcard_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/files/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='task',
            name='google_drive_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Диск'),
        ),
    ]
