# Generated by Django 4.2.25 on 2025-11-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_attachment_task_google_drive_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcard',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AddField(
            model_name='eventcard',
            name='plan_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='event_plans/', verbose_name='План мероприятия'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='plan_rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='plan_reviewed_by_deputy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_reviews', to='tasks.employee'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='plan_reviewed_by_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_reviews', to='tasks.employee'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='plan_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('rejected', 'Отклонён'), ('approved', 'Утверждён')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='plan_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_cards', to='tasks.department'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='shared_departments',
            field=models.ManyToManyField(blank=True, related_name='shared_cards', to='tasks.department'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='visible',
            field=models.BooleanField(default=False, help_text='Доступна ли карточка для создания задач (после утверждения)'),
        ),
    ]
