# Generated by Django 4.2.25 on 2025-11-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_eventcard_options_eventcard_plan_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('normal', 'Обычная'), ('urgent', 'Срочная')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('regular', 'Обычная'), ('approval', 'Согласование')], default='regular', max_length=20),
        ),
    ]
