# Generated by Django 4.2.25 on 2025-11-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_priority_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='delegate_to',
            field=models.ForeignKey(blank=True, help_text='Кому временно переданы полномочия этого сотрудника.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_from', to='tasks.employee', verbose_name='Замещающий сотрудник'),
        ),
        migrations.AddField(
            model_name='employee',
            name='delegate_until',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания замещения'),
        ),
    ]
