# Generated by Django 4.2.25 on 2025-11-07 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='current_approver_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='final_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_to_finalize', to='tasks.employee', verbose_name='Утверждающий'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='has_plan',
            field=models.BooleanField(default=False, verbose_name='С планом мероприятия'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='is_fully_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CardApproverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.eventcard')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.employee')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='eventcard',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approver_cards', through='tasks.CardApproverOrder', to='tasks.employee'),
        ),
    ]
