# Generated by Django 4.2.25 on 2025-11-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_eventcard_current_approver_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapproverorder',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
