# Generated by Django 4.2.25 on 2025-11-10 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_cardapproverorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='final_approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['deputy', 'director']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_cards', to='tasks.employee', verbose_name='Финальный утверждающий'),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cards', to='tasks.category', verbose_name='Категории'),
        ),
    ]
