# Generated by Django 4.2.25 on 2025-11-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_category_eventcard_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='final_approver',
            field=models.ForeignKey(limit_choices_to={'role__in': ['deputy', 'director']}, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_cards', to='tasks.employee', verbose_name='Финальный утверждающий'),
        ),
    ]
