# Generated by Django 4.2.25 on 2025-11-10 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_eventcard_final_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='final_approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['deputy', 'director']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_cards', to='tasks.employee', verbose_name='Финальный утверждающий'),
        ),
    ]
