# Generated by Django 4.2.25 on 2025-11-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_taskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('sent_for_review', 'Отправлена на согласование'), ('under_review', 'На рассмотрении'), ('done', 'Выполнена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначена'), ('taken', 'Взята в работу'), ('redirected', 'Перенаправлена'), ('executed ', 'Исполнена'), ('done', 'Завершена')], max_length=50),
        ),
    ]
