# Generated by Django 4.2.25 on 2025-11-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_completed_at_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('regular', 'Обычная'), ('approval', 'Согласование плана'), ('review', 'Согласование')], default='regular', max_length=20),
        ),
    ]
