# Generated by Django 6.0 on 2025-12-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_add_time_to_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий проверяющего'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('sent_for_review', 'Отправлена на согласование'), ('under_review', 'На рассмотрении'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('regular', 'Обычная'), ('approval', 'Согласование плана'), ('review', 'Согласование')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначена'), ('taken', 'Взята в работу'), ('sent_for_review', 'Отправлена на согласование'), ('under_review', 'На рассмотрении'), ('rejected', 'Отклонена'), ('redirected', 'Перенаправлена'), ('executed', 'Исполнена'), ('done', 'Завершена')], max_length=50),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/execution_files/')),
                ('link', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.employee')),
            ],
        ),
    ]
