# Generated by Django 4.2.25 on 2025-11-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('sent_for_review', 'Отправлена на согласование'), ('under_review', 'На рассмотрении'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
