# Generated by Django 4.2.25 on 2025-11-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначена'), ('taken', 'Взята в работу'), ('sent_for_review', 'Отправлена на согласование'), ('under_review', 'На рассмотрении'), ('rejected', 'Отклонена'), ('redirected', 'Перенаправлена'), ('executed', 'Исполнена'), ('done', 'Завершена')], max_length=50),
        ),
    ]
