# Generated by Django 4.2.25 on 2025-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_taskhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий проверяющего'),
        ),
    ]
