# Generated by Django 4.2.24 on 2026-01-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_taskhistory_action_taskcomment_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='redirect_chain',
            field=models.JSONField(blank=True, default=list, help_text='Список ID сотрудников в порядке перенаправления задачи', verbose_name='Цепочка перенаправлений'),
        ),
        migrations.AddField(
            model_name='task',
            name='redirected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_tasks', to='tasks.employee', verbose_name='Перенаправлена от'),
        ),
    ]
