# Generated by Django 4.2.25 on 2025-11-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shortname',
            field=models.CharField(default='short', max_length=255),
        ),
    ]
