# Generated by Django 4.2.24 on 2026-01-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_task_redirect_chain_task_redirected_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AddField(
            model_name='department',
            name='priority',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше приоритет. Используется для сортировки отделов.', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='employee',
            name='internal_phone',
            field=models.CharField(blank=True, help_text='Внутренний номер телефона сотрудника', max_length=20, null=True, verbose_name='Внутренний телефон'),
        ),
    ]
