# Generated by Django 4.2.25 on 2025-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_department_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='plan_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('rejected', 'Отклонён'), ('approved', 'Утверждён'), ('rework ', 'На доработке')], default='draft', max_length=20),
        ),
    ]
