# Generated by Django 6.0 on 2026-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_department_options_department_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, help_text='Имя сотрудника', max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(blank=True, help_text='Отчество сотрудника', max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, help_text='Фамилия сотрудника', max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
