# Generated by Django 4.2.25 on 2025-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_eventcard_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='plan_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('rejected', 'Отклонён'), ('approved', 'Утверждён')], default='draft', max_length=20),
        ),
    ]
