# Generated by Django 6.0 on 2026-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_employee_external_phone_employee_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_phone',
            field=models.CharField(blank=True, help_text='Рабочий номер телефона сотрудника', max_length=20, null=True, verbose_name='Рабочий номер'),
        ),
    ]
