# Generated by Django 6.0 on 2026-01-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_add_external_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_approval_chain',
            field=models.JSONField(blank=True, default=list, help_text='Список ID сотрудников в порядке согласования создания задачи', verbose_name='Цепочка согласования создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='current_approval_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Текущий индекс согласующего по созданию'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_according_to_plan',
            field=models.BooleanField(default=True, help_text='Флаг, создана ли задача согласно плана', verbose_name='Согласно плана'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='tasks.task', verbose_name='Связанная задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('creation_approval', 'Согласование создания'), ('execution_review', 'Проверка выполнения')], max_length=20, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('sent_for_review', 'Отправлена на согласование'), ('under_review', 'На рассмотрении'), ('done', 'Выполнена'), ('rejected', 'Отклонена'), ('pending', 'Ожидает согласования'), ('revision', 'На пересмотрении')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('regular', 'Обычная'), ('approval', 'Согласование плана'), ('review', 'Согласование выполнения'), ('task_approval', 'Согласование задачи')], default='regular', max_length=20),
        ),
    ]
