# Generated by Django 6.0 on 2026-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_task_creation_approval_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('sent_for_review', 'Отправлено на проверку'), ('under_review', 'На проверке'), ('done', 'Выполнена'), ('rejected', 'Отклонена'), ('pending', 'На согласовании'), ('revision', 'На пересмотрении'), ('send_for_approve', 'Отправлено на согласование')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
