# Generated by Django 6.0 on 2026-01-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначена'), ('taken', 'Взята в работу'), ('sent_for_review', 'Отправлена на проверку'), ('under_review', 'На проверке'), ('rejected', 'Отклонена'), ('redirected', 'Перенаправлена'), ('executed', 'Исполнена'), ('done', 'Завершена'), ('execution_updated', 'Обновлено выполнение'), ('approved', 'Утверждена'), ('completed', 'Завершена'), ('delegated', 'Делегирована'), ('sent_for_approve', 'Отправлена на согласование'), ('pending', 'На согласовании'), ('revision', 'На пересмотрении')], max_length=50),
        ),
    ]
