# Generated by Django 6.0 on 2026-01-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_taskhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewers_chain',
            field=models.JSONField(blank=True, default=list, help_text='Список ID сотрудников в порядке проверки выполнения задачи', verbose_name='Цепочка проверяющих'),
        ),
    ]
