# Generated by Django 4.2.25 on 2026-01-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_taskhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shortname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое название'),
        ),
    ]
