# Generated by Django 6.0 on 2026-02-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_migrate_chain_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskapprovalchain',
            new_name='tasks_taska_task_id_75bc5b_idx',
            old_name='tasks_task__task_s_idx',
        ),
        migrations.RenameIndex(
            model_name='taskapprovalchain',
            new_name='tasks_taska_approve_53c399_idx',
            old_name='tasks_task__appro_idx',
        ),
        migrations.RenameIndex(
            model_name='taskredirectchain',
            new_name='tasks_taskr_from_em_7b09bb_idx',
            old_name='tasks_task__from_to_idx',
        ),
        migrations.RenameIndex(
            model_name='taskreviewchain',
            new_name='tasks_taskr_task_id_563d68_idx',
            old_name='tasks_task__task_s_rev_idx',
        ),
        migrations.RenameIndex(
            model_name='taskreviewchain',
            new_name='tasks_taskr_reviewe_b98bd7_idx',
            old_name='tasks_task__rev_s_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='final_reviewer',
            field=models.ForeignKey(blank=True, help_text='Финальный проверяющий (после создателя)', limit_choices_to={'role__in': ['deputy', 'director']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_review_tasks', to='tasks.employee', verbose_name='Финальный проверяющий'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_self',
            field=models.BooleanField(default=True, help_text='Создатель проверяет выполнение (первым в цепочке)', verbose_name='Проверить самому'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначена'), ('taken', 'Взята в работу'), ('sent_for_review', 'Отправлена на проверку'), ('under_review', 'На проверке'), ('rejected', 'Отклонена'), ('redirected', 'Перенаправлена'), ('return_redirect', 'Возврат перенаправления'), ('executed', 'Исполнена'), ('done', 'Завершена'), ('execution_updated', 'Обновлено выполнение'), ('updated', 'Отредактирована'), ('approved', 'Утверждена'), ('completed', 'Завершена'), ('delegated', 'Делегирована'), ('sent_for_approve', 'Отправлена на согласование'), ('pending', 'На согласовании'), ('revision', 'На пересмотрении')], max_length=50),
        ),
    ]
