# Generated by Django 4.2.25 on 2026-03-12 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0052_add_review_self_final_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц (1-12)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда сформирован')),
                ('formula_version', models.CharField(default='v1', help_text='Позволяет менять формулу в будущем, не ломая старые отчеты.', max_length=20, verbose_name='Версия формулы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Сформирован'), ('failed', 'Ошибка формирования')], default='completed', max_length=20, verbose_name='Статус формирования')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Служебное сообщение / ошибка')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_reports', to=settings.AUTH_USER_MODEL, verbose_name='Кто сформировал')),
            ],
            options={
                'verbose_name': 'KPI отчёт',
                'verbose_name_plural': 'KPI отчёты',
                'ordering': ['-year', '-month', '-generated_at'],
                'unique_together': {('year', 'month', 'formula_version')},
            },
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_snapshot', models.CharField(choices=[('director', 'Директор'), ('deputy', 'Заместитель директора'), ('head', 'Руководитель отдела'), ('senior', 'Сотрудник с повышенными правами'), ('staff', 'Обычный сотрудник')], max_length=20, verbose_name='Роль на момент расчета')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Итоговый балл (0-100)')),
                ('metrics_json', models.JSONField(blank=True, default=dict, help_text='Вспомогательные метрики, на основе которых считается KPI.', verbose_name='Сырые метрики')),
                ('breakdown_json', models.JSONField(blank=True, default=dict, help_text="Например: {'timeliness': 42.5, 'completion': 30, 'workload': 15, ...}.", verbose_name='Разложение балла')),
                ('flags_json', models.JSONField(blank=True, default=dict, verbose_name='Флаги качества данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_results', to='tasks.department', verbose_name='Отдел (срез на момент расчета)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_results', to='tasks.employee', verbose_name='Сотрудник')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tasks.kpireport', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'KPI результат',
                'verbose_name_plural': 'KPI результаты',
                'ordering': ['employee__department__priority', 'employee__department__name', 'employee__middlename'],
                'unique_together': {('report', 'employee')},
            },
        ),
    ]
