# Generated by Django 6.0.3 on 2026-03-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_kpireport_kpiresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], help_text='Заполняется руководителем/инициатором; при отсутствии используется вычисляемая сложность в KPI v2.', max_length=20, null=True, verbose_name='Сложность задачи'),
        ),
        migrations.CreateModel(
            name='KPIRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('deputy', 'Заместитель директора'), ('head', 'Руководитель отдела'), ('senior', 'Сотрудник с повышенными правами'), ('staff', 'Обычный сотрудник')], max_length=20, verbose_name='Роль')),
                ('formula_version', models.CharField(choices=[('v1', 'Формула v1 (наследие)'), ('v2', 'Формула v2 (расширенная)')], default='v2', max_length=20, verbose_name='Версия формулы')),
                ('positive_cap_max', models.DecimalField(decimal_places=2, default=100.0, help_text='Ограничение итогового позитивного балла перед применением штрафов.', max_digits=5, verbose_name='Максимальный позитивный потолок')),
                ('penalty_min_factor', models.DecimalField(decimal_places=2, default=0.6, help_text='Например, 0.60 означает, что суммарные штрафы не могут снизить балл более чем на 40%.', max_digits=4, verbose_name='Минимальный коэффициент после штрафов')),
                ('positive_weights', models.JSONField(blank=True, default=dict, help_text="Например: {'workload_volume': 0.4, 'quality': 0.3, 'timeliness': 0.3}.", verbose_name='Веса позитивных блоков')),
                ('penalty_weights', models.JSONField(blank=True, default=dict, help_text="Например: {'overdue_ratio': 0.4, 'rejected_ratio': 0.3, 'urgent_miss_ratio': 0.3}.", verbose_name='Веса штрафов')),
            ],
            options={
                'verbose_name': 'KPI конфигурация роли',
                'verbose_name_plural': 'KPI конфигурации ролей',
                'unique_together': {('role', 'formula_version')},
            },
        ),
    ]
